{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.appName }}'
  labels:
    app: '{{ .Values.appName }}'
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}