{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}"
spec:
  selector:
    app: "{{ .Values.appName }}"
  type: '{{ .Values.service.type }}'
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
