on:
  push

jobs:
  auth0-set-application-uris:

    runs-on: 
      - ubuntu-latest
    
    steps:
      - uses: singingwolfboy/auth0-set-application-uris@v1
        with:
          auth0-domain: "dev-8dot8lae.us.auth0.com"
          auth0-client-id: "ZCSj7d5zdSErdR8DaOt0WpOhxI5ocsvI"
          auth0-client-secret: "9y6QEmToPACOlusfv8ZVbtFe9oBZ3sg5zsiVftOiGmcRKAYXBYtzVZ66ynyNCcFn"
          auth0-target-client-id: "DXjOmq8cMccrhs5PYPVRAErVuWQ0zTQC"
          callback-url-template: "https://pr-{{ pull_request.number }}.example.com/callback"
          logout-url-template: "https://pr-{{ pull_request.number }}.example.com/"
