on:
  push:
    branches:
      - main
      - master
      
jobs:
  callerJob:
    runs-on:
      - ubuntu-latest
    steps:
      - name: call action2
        uses: "./.github/template/deploy"
    
