name: Release Deploy - Pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: false

on:
  workflow_dispatch:

jobs:
  cut-prerelease:
    runs-on: ubuntu-latest
    
    steps:
     - name: print
       run: |
        echo ${{ secrets[format('{0}_WORD', 'dev')] }}
        echo ${{ env[format('{0}_word', 'dev')] }}
        echo ${{ vars[format('{0}_word', 'dev')] }}
