name: Release Deploy - Pipeline

on:
  push:
    paths: 
      - nginx/config
      - menginx/config

jobs:
  cut-prerelease:
    runs-on: ubuntu-latest
    
    steps:
     - name: print payload
       run: |
        echo $GITHUB_EVENT_PATH
