name: Release Deploy - Pipeline

on:
  push:
  
jobs:
  cut-prerelease:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
       

      - name: Changed Files
        uses: tj-actions/changed-files@v36.4.1
        
