name: Release Deploy - Pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: false

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-+\b[a-z0-9]+\b'

jobs:
  cut-prerelease:
    name: Cut prerelease from tag
    uses: Hakob771/test/.github/workflows/main/cutter.yml@main
    with:
      release_tag: ${{ github.ref_name }}

  print-result:
    needs: 
      - cut-prerelease
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: Print from last job
        run: echo ${{ needs.cut-prerelease.outputs.environment_name }}
