name: Release Deploy - Pipeline

on:
  push:
  
jobs:
  cut-prerelease:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
       

      - name: Print changed file name
        uses: juliangruber/changed-files@v1
        id: changed
        with:
          number: 1

      - name: Output file names
        run: |
          echo "Changed file names:"
          echo "${{ steps.changed.outputs.files }}"
