name: Release Deploy - Pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: false

on:
  push:
    paths: 
      - nginx/config
      - menginx/config

jobs:
  cut-prerelease:
    runs-on: ubuntu-latest
    
    steps:
     - name: print payload
       run: |
        echo ${{ toJSON(github.event) }}
