on:
  workflow_dispatch:

jobs:
  get_keys_in_list:
    runs-on:
      - ubuntu-latest
      
    steps:
    - name: Read JSON organizational variable
      run: |
        json="${{ vars.ENVS }}"
        echo "$json" # For verification purposes

    - name: Use jq on JSON organizational variable
      run: |
        json="${{ vars.ENVS }}"
        keys=$(echo "$json" | jq 'keys[]')
        echo "$keys" # For verification purposes
