on:
  workflow_dispatch:

jobs:
  get_keys_in_list:
    runs-on:
      - ubuntu-latest
      
    steps:
    - name: Read JSON to file
      run: |
        echo ${{ vars.ENVS }} > file.json
        jq keys[] file.json
