on:
  workflow_dispatch:

jobs:
  get_keys_in_list:
    runs-on:
      - ubuntu-latest
    
    steps:
    - name: Read Key
      id: keys
      run: |
        keys=$(echo -e '${{ vars.ENVS }}' | jq 'keys | map(. + "")')
