on:
  workflow_dispatch:

jobs:
  get_keys_in_list:
    runs-on:
      - ubuntu-latest
    
    outputs:
      environments: ${{ steps.keys.outputs.envs }}
    
    steps:
    - name: Read Key
      id: keys
      run: |
        echo "envs=${{ fromJSON($(echo -e '${{ vars.ENVS }}' | jq 'keys | map(. + "")')) }}"
