name: Unit Tests

on:
  workflow_dispatch:
  
jobs:
  run-test:
    name: 'A'
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: 'export variable'
        run:
          export APP_NAME=jango
          
      - name: 'echo variable'
        run:
          echo $APP_NAME
