name: 'Status Check'

on:
  push:
    tags:
      - 'v111'

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    environment: 'test'

    steps:
      - name: Print hello
        run: | 
          echo ${{ fromJSON(github) }}
