name: Unit Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: false

on:
  workflow_call:

jobs:
  run-test:
    name: 'Run Unit Tests'
    runs-on:
      - ubuntu-latest
    steps:
      - name: check envsubst
        run: |
          envsubst
