name: 'Nested'

on:
  push:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - name: check
        run: |
          tmp=false
          for team in a b c
          do
            if [[ ${{ contains('hello', $team) }} ]]
            then
              $tmp=true
            fi
          done
          if [[ $tmp == true ]]
          then
            exit 0
          else
            exit 1
          fi
  job2:
    runs-on:
      - ubuntu-latest
    needs:
      - job1

    steps:
      - name: print hello world
        run: |
          echo hello world
