name: Unit Tests

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
  
jobs:
  run-test:
    name: 'A'
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: 'yq'
        run: |
          yq -i '.korio.image.tag = "tagmag"' file.yaml
          cat file.yaml
