name: Unit Tests

on:
  push:

jobs:
  run-test:
    name: 'Run Unit Tests'
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: 'check envsubst'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
