name: Unit Tests

on:
  workflow_dispatch:
    inputs:
      bool:
        options:
          - "enable"
          - "disable"
        default: "enable"
        required: true
        type: choice

jobs:
  run-test:
    name: 'Run Unit Tests'
    runs-on:
      - ubuntu-latest
    steps:
      - name: check envsubst
        run: |
          envsubst
