name: 'Nested'

on:
  push:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - name: check
        run: |
          for team in ${{ fromJSON(vars.TEAMS)[stage] }}
          do
            echo $team
          done
