on:
  push:
    branches:
      - main

jobs:
  exit:
    name: Exit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tmp: [1, 1, 0, 1]
    outputs:
      exit-code: ${{ steps.set_exit_code.outputs.exit-code }}
    steps:
      - name: Set Exit Code
        id: set_exit_code
        run: |
          sleep 30
          echo "::set-output name=exit-code::${{ matrix.tmp }}"
      - name: 'Exit'
        run: exit ${{ matrix.tmp }}

  continue:
    name: Continue
    runs-on: ubuntu-latest
    steps:
      - name: 'Continue'
        run: echo "Continue"
