name: 'Nested'

on:
  workflow_call:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: tspascoal/get-user-teams-membership@v2
        with:
          echo: ${{ toJSON(github) }}
