name: Publish ACR

on:
  workflow_dispatch:

jobs:
  build:
    name: publish acr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout repo

      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: esim
        run: |
          helm chart --help
          helm chart push --help
          
