on:
  push:

jobs:
  exit:
    name: exit
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.exit.output.val }}
    strategy:
      matrix:
        tmp: [true, false, TRUE, false]
    steps:
      - name: 'Exit'
        id: exit
        run: |
          echo "val=${{ matrix.tmp }}" >> $GITHUB_OUTPUT
      - name: 'Print step up'
        run: |
          echo ${{ steps.exit.outputs.val }}

  continue:
    name: 'Continue'
    runs-on: ubuntu-latest
    needs:
      - exit
    steps:
      - name: 'Continue'
        run: | 
          echo ${{ toJSON(needs.exit) }}
