name: 'Nested'

on:
  release:
    types: 
      - released

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout Repo
        run: |
          echo ${{ toJSON(github.event.tag_name) }}
