name: test

on:
  push:
    tags:
    - '[0-9].+[0-9].+[0-9]+-+rc+[0-9]'


jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout repo

      - name: print payload
        run: |  
          echo ${{ toJson(github.event) }}
