name: test

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout repo

      - name: run exit
        run: |
          exit 199

      - name: continue
        continue-on-error: true
        run: |
          echo barev
