name: 'Nested'

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - name: check
        run: |
          git fetch --tags && git describe --tags $(git rev-list --tags --max-count=1)
