name: 'Nested'

on:
  workflow_call:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v3
    
      - name: 'Print payload'
        run: |
          echo: ${{ toJSON(github.event.repository.name) }}
