name: 'Status Check'

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: tspascoal/get-user-teams-membership@v2
        with:
          username: ${{ github.actor }}
          GITHUB_TOKEN: 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
