name: Unit Tests

on:
  workflow_dispatch:
  
jobs:
  run-test:
    name: 'A'
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: 'envsubst'
        env:
          APP_NAME: 'Jango'
        run: |
          envsubst < file > file2
          cat file2
