name: test

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout repo

      - name: run echo
        run: |
          echo ${GITHUB_SHA:0:8}
