on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
      - ubuntu-latest
    
    steps:
      - name: Check member exists in GitHub Team
        uses: bryantson/check-member-exists-in-team-actions@1.0
        with:
          team_slug: devops
          org_slug: Hakob771
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          username: hakmkoyan

      - name: Print whether member exists
        run: |
          echo "Does member exists: ${{ steps.check-member.outputs.exists-in-team }}"
