name: Unit Tests

on:
  workflow_dispatch:
    inputs:
      enable:
        default: "true"
        required: true
        options:
          - "true"
          - "false"
        type: choice

jobs:
  run-test:
    if: contains("false", "true")
    name: 'Run Unit Tests'
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: 'check envsubst'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
