name: Publish ACR

on:
  workflow_dispatch:
    inputs:
      exit_code:
        required: true
        type: number

jobs:
  build:
    name: publish acr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout repo

      - name: run exit
        run: |
          exit ${{ inputs.exit_code }}
