name: 'Nested'

on:
  push:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    strategy:
      matrix: 
        alpha: ["a", "b", "c"]

    steps:
      - name: check
        run: |
          if [[ ${{ contains('ab', matrix.alpha) }} ]]
          then
            exit 0
          fi
  job2:
    runs-on:
      - ubuntu-latest
    needs:
      - job1

    steps:
      - name: print hello world
        run: |
          echo hello world
