on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Check Team Members
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TEAM_NAME="my-team"
          TEAM_MEMBERS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/orgs/{org}/teams/$TEAM_NAME/members")
          echo "Team Members: $TEAM_MEMBERS"
