on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
      - ubuntu-latest
    
    steps:
      - name: Hello World
        run: |
          curl -s -w "%{http_code}\n" -o /dev/null \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/"$Hakob771"/teams/"$devops"/memberships/"$hakmkoyan"
