on:
  push:

jobs:
  exit:
    name: exit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tmp: [1 1 0 1]
    steps:
      - name: 'Exit'
        run: |
          exit ${{ matrix.tmp }}

  continue:
    name: 'Continue'
    runs-on: ubuntu-latest
    steps:
      - name: 'Continue'
        run: |
          echo continue
