name: 'Status Check'

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    environment: 'test'

    steps:
      - name: Print hello
        run: | 
          echo ${{ fromJSON(github) }}
