on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - name: print teams
        run: |
          TEAM_NAME="devops"
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          TEAM_MEMBERS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN "https://api.github.com/orgs/Hakob771/teams/$TEAM_NAME/members")
          echo "Team Members: $TEAM_MEMBERS"
