name: 'Nested'

on:
  workflow_call:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    strategy:
      matrix: 
        alpha: ["a", "b", "c"]

    steps:
      - name: check
        run: |
          ${{ contains(matrix.alpha, "good bye") }}
  job2:
    runs-on:
      - ubuntu-latest

    steps:
      - name: print hello world
        run: |
          echo hello world
