name: 'Nested'

on:
  push:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - name: check
        run: |
          for team in `jq -r '.stage[]' ${{ formatJSON(vars.TEAMS) }}`
          do
            echo $team
          done
