name: 'Status Check'

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Print hello
        run: | 
          echo hello

  job2:
    needs:
      - job1
    runs-on:
      - ubuntu-latest
    environment: test
    
    steps:
      - name: Wait
        run: | 
          echo wait

  job3:
    needs:
      - job2
    runs-on:
      - ubuntu-latest

    steps:
      - name: Continue
        run: |
          echo continue
