name: Merge 

on:
  push:
    branches: 
      - main
  pull_request:
    types: 
      - closed
      
jobs:
  mergeAndDeleteBranch:
    runs-on: ubuntu-latest
    
    steps:
      - name: just
        run: echo ${{ github.event }}
