name: Merge 

on:  
  pull_request:
    types: 
      - closed
      
jobs:
  mergeAndDeleteBranch:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: get branch name 2tj-actions/branch-names@v6
        id: branch_name
        uses: tj-actions/branch-names@v6
  
      - name: Merge and Delete
        if: steps.branch_name.outputs.current_branch != 'donotremove'
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      
      - name: Merge
        if: steps.branch_name.outputs.current_branch == 'donotremove'
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: uat
          github_token: ${{ github.GIT_TOKEN }}
