name: Merge workflow

on:  
  push:
    branches: 
      - main
      
jobs:
  make_output:
    runs-on: [ubuntu-latest]
    steps:
      - name: make out
        run: echo "Anun=Hakob" >>$GITHUB_OUTPUT
    
  get_output:
    runs-on: [ubuntu-latest]
    steps:
      - name: print out
        run: echo $GITHUB_OUTPUT
