name: Merge workflow

on:  
  push:
    branches: 
      - main
      
jobs:
  check:
    runs-on: [ubuntu-latest]
    steps:
      - name: check secret
        run: echo "${secrets.GIT_TOKEN}" > secret
        
      - name: cat secret
        run: ls; cat secret
