on:
  workflow_dispatch:
  push:
  
jobs:
  job1:
    runs-on:
      - ubuntu-latest
      
    outputs:
      environments: "${{ steps.get-env-names.outputs.envs }}"
      
    steps:
      - name: 'Get environments'
        id: get-env-names
        run: |
          keys=$(echo -e '${{ vars.ENVS }}' | jq 'keys | map(. + "")')
          echo """envs="$keys"""" >> $GITHUB_OUTPUT
          
  job2:
    needs:
      - job1
      
    runs-on:
      - ubuntu-latest
    
    strategy:
      matrix:
        environments: ${{ needs.job1.outputs.environments }}
        
    steps:
      - name: print
        run: |
          echo ${{ matrix.environments }}
