on:
  workflow_dispatch:
  push:
  
jobs:
  test:
    runs-on: 
      - ubuntu-latest
    strategy:
      matrix:
        environments: ['dev2', 'sqa2']
        include:
          - environments: ${{ matrix.environments }}
            hosts: ${{ vars[format('HOST_{0}', matrix.environments)] }}
      
    steps:
      - name: Print out
        run: |
          echo barev
