on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: 
      - self-hosted
    strategy:
      matrix:
        environments: [dev2, sqa2]
        sub_environments: [smoke, live]
      
    steps:
      - name: Print out
        run: |
          echo ${{ matrix.environments }}
          echo ${{ matrix.sub_environments }}
