on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: dev2

jobs:
  test:
    runs-on: 
      - self-hosted
    strategy:
      matrix:
        environments: ${{ fromJSON(vars.VMS) }}
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      
      - name: "Install keys"
        run: |
          echo ${{ fromJSON(github) }}
