name: Create Release on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  get-current-label:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    runs-on:
      - ubuntu-latest
      
    steps:

      - name: get labels
        id: hello
        run: |
          if [ ${{ contains(github.event.pull_request.labels.*.name, 'bug'}} ]
          then
            echo "version=bug" >> $GITHUB_OUTPUT
          elif [ ${{ contains(github.event.pull_request.labels.*.name, 'documentation'}} ]
          then
            echo "version=documentation" >> $GITHUB_OUTPUT
          else
            echo "version=minor" >> $GITHUB_OUTPUT
          fi
          
      - name: print labels
        run: echo ${{ steps.hello.outputs.version }}
          
          
