name: Create Release on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  get-current-label:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    runs-on:
      - ubuntu-latest
      
    steps:
      - name: get label
        run: ${{ contains(github.event.pull_request.labels.*.name, 'bug') }}

      - name: get labels
        run: |
          echo ${{ github.event.pull_request }}
