on:
  workflow_run:
    workflows: [Merge workflow]
    types:
      - completed
    
jobs:
  my_job:
    if: github.event.workflow_run.success == 'success'
  
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: helloworld
        run: echo hello world
