on:
  push:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    steps:
      - name: 'print'
        run: |
          from i in ${{ fromJSON(vars.ENVS).dev2 }}
          do
            echo $i
          done
