on:
  push:

jobs:
  job1:
    runs-on:
      - ubuntu-latest

    strategy:
      matrix:
        subenvs: ${{ fromJSON(vars.ENVS).dev2 }}

    steps:
      - name: 'print'
        run: |
          echo ${{ vars.ENVS.dev2 }}
